[package]
edition = "2021"
name = "std-rs"
version = "0.1.0"

[features]
default = []
serde = ["dep:serde"]

[dependencies]
base64 = "0.22.1"
derive-new = { version = "0.7.0" }
serde = { version = "1.0.215", optional = true }

[dev-dependencies]
serde_json = "1.0.133"
