[package]
edition = "2021"
name = "std-rs"
version = "0.1.0"

[dependencies]
base64 = "0.22.1"
derive-new = {version = "0.7.0"}
rusty_paseto = "0.7.1"
serde = "1.0.215"

[dev-dependencies]
serde_json = "1.0.133"
